//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentdal
{
    using System;
    using System.Collections.Generic;
    
    public partial class @class
    {
        public decimal class_id { get; set; }
        public string class_name { get; set; }
    }
}
