//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace school_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public decimal student_id { get; set; }
        public string student_name { get; set; }
        public string student_address { get; set; }
        public string student_email { get; set; }
        public string student_class { get; set; }
    }
}
